# -*- coding: utf-8 -*-
"""Avaliacao_Clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicEOMvEeXqzhSjc8oc_0RL2Hd4vkROU
"""

!pip install -q streamlit
!npm install -q -g localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import re
# 
# # Configuração visual inicial da página no Streamlit
# st.set_page_config(
#     page_title="Classificador de Sentimentos",
#     page_icon="📊",
#     layout="centered"
# )
# 
# # Conjuntos globais de palavras-chave
# POSITIVE_KEYWORDS = {
#     "excelente", "ótimo", "otimo", "bom", "boa", "adorei", "gostei",
#     "recomendo", "incrível", "incrivel", "rápido", "rapido", "perfeito",
#     "eficiente", "satisfeito", "maravilhoso", "qualidade", "ótima", "otima"
# }
# 
# NEGATIVE_KEYWORDS = {
#     "ruim", "péssimo", "pessimo", "horrível", "horrivel", "demorado",
#     "atraso", "defeito", "decepcionado", "decepção", "decepcao", "odiei",
#     "pior", "cancelar", "problema", "péssima", "pessima", "lento"
# }
# 
# # Palavras de negação que invertem a polaridade do termo que as segue
# NEGATION_WORDS = {"não", "nao", "nunca", "jamais", "sem", "nada"}
# 
# 
# def analyze_sentiment(text: str) -> dict:
#     """
#     Analisa o texto considerando modificadores de negação antes de
#     incrementar os contadores de sentimento.
#     """
#     try:
#         # Validação para tratar entradas vazias
#         if not text or not text.strip():
#             return {
#                 "sentiment": "Neutro",
#                 "pos_count": 0,
#                 "neg_count": 0,
#                 "pos_found": [],
#                 "neg_found": []
#             }
# 
#         # Normalização do texto
#         clean_text = text.lower()
#         words = re.findall(r'\b\w+\b', clean_text)
# 
#         pos_found = []
#         neg_found = []
# 
#         # Percorremos as palavras verificando o contexto anterior
#         for i, word in enumerate(words):
#             # Verifica se existe uma negação 1 ou 2 posições atrás (ex: "não bom" ou "não é bom")
#             has_negation = False
#             if i > 0 and words[i - 1] in NEGATION_WORDS:
#                 has_negation = True
#             elif i > 1 and words[i - 2] in NEGATION_WORDS:
#                 has_negation = True
# 
#             # Processamento de termos positivos
#             if word in POSITIVE_KEYWORDS:
#                 if has_negation:
#                     # Inverte para negativo se houver negação antes
#                     neg_found.append(f"não {word}")
#                 else:
#                     pos_found.append(word)
# 
#             # Processamento de termos negativos
#             elif word in NEGATIVE_KEYWORDS:
#                 if has_negation:
#                     # Inverte para positivo se houver negação antes (ex: "não é ruim")
#                     pos_found.append(f"não {word}")
#                 else:
#                     neg_found.append(word)
# 
#         pos_count = len(pos_found)
#         neg_count = len(neg_found)
# 
#         # Árvore de decisão condicional
#         if pos_count > neg_count:
#             sentiment = "Positivo"
#         elif neg_count > pos_count:
#             sentiment = "Negativo"
#         else:
#             sentiment = "Neutro"
# 
#         return {
#             "sentiment": sentiment,
#             "pos_count": pos_count,
#             "neg_count": neg_count,
#             "pos_found": pos_found,
#             "neg_found": neg_found
#         }
# 
#     except Exception as e:
#         # Tratamento de exceções
#         st.error(f"Erro ao processar a análise: {str(e)}")
#         return {
#             "sentiment": "Erro",
#             "pos_count": 0,
#             "neg_count": 0,
#             "pos_found": [],
#             "neg_found": []
#         }
# 
# 
# def main():
#     """
#     Função principal de construção da interface no Streamlit.
#     """
#     try:
#         st.title("📊 Classificador de Sentimentos de Clientes")
#         st.caption("Ferramenta para análise rápida da equipa de Marketing")
# 
#         user_comment = st.text_area(
#             "Digite o comentário do cliente:",
#             height=120,
#             placeholder="Exemplo: O produto não é bom..."
#         )
# 
#         if st.button("Analisar Sentimento", type="primary"):
#             if user_comment.strip():
#                 result = analyze_sentiment(user_comment)
#                 sentiment = result["sentiment"]
# 
#                 st.divider()
# 
#                 if sentiment == "Positivo":
#                     st.success("🟢 **Sentimento Classificado: POSITIVO**")
#                 elif sentiment == "Negativo":
#                     st.error("🔴 **Sentimento Classificado: NEGATIVO**")
#                 else:
#                     st.warning("🟡 **Sentimento Classificado: NEUTRO**")
# 
#                 col1, col2 = st.columns(2)
#                 with col1:
#                     st.metric("Termos Positivos", result["pos_count"])
#                     if result["pos_found"]:
#                         st.caption(f"Encontrados: {', '.join(result['pos_found'])}")
# 
#                 with col2:
#                     st.metric("Termos Negativos", result["neg_count"])
#                     if result["neg_found"]:
#                         st.caption(f"Encontrados: {', '.join(result['neg_found'])}")
#             else:
#                 st.info("Digite uma mensagem no campo acima antes de clicar no botão.")
# 
#     except Exception as e:
#         st.error(f"Erro na interface do Streamlit: {str(e)}")
# 
# 
# if __name__ == "__main__":
#     main()

# 1. Baixa e instala a ferramenta oficial da Cloudflare no Colab
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

# 2. Inicia o Streamlit em segundo plano
!streamlit run app.py &>/content/logs.txt &

# 3. Cria o túnel público seguro
!cloudflared tunnel --url http://localhost:8501

