# -*- coding: utf-8 -*-
"""Conta_Luz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicEOMvEeXqzhSjc8oc_0RL2Hd4vkROU
"""

!pip install -q streamlit
!npm install -q -g localtunnel

!streamlit run app.py &>/content/logs.txt &
!curl -s https://loca.lt/mytunnelpassword

"""
Previsão da Conta de Luz no Verão
---------------------------------
O usuário informa quantas horas por dia usa o ar-condicionado.
Um modelo de regressão linear (TensorFlow) projeta o valor da conta do mês
e o app mostra, em um gráfico de linha, como o gasto evolui dia a dia.

Estrutura:
    gerar_dados()       -> cria dados de treino (simulados)
    treinar_modelo()    -> normaliza, treina e extrai os parâmetros da reta
    prever_conta()      -> projeta a conta mensal para um total de horas
    montar_evolucao()   -> calcula o gasto acumulado dia a dia (para o gráfico)
    main()              -> interface Streamlit
"""

import numpy as np
import pandas as pd
import streamlit as st
import tensorflow as tf

SEED = 42                # semente fixa: resultados reproduzíveis
DIAS_MES = 30            # simplificação: todo mês tem 30 dias
tf.keras.utils.set_random_seed(SEED)


# ---------------------------------------------------------------------------
# 1) DADOS
# ---------------------------------------------------------------------------
def gerar_dados(n_amostras: int = 300):
    """Simula contas de luz de vários meses de verão.

    Relação "verdadeira" usada na simulação (o modelo não a conhece):
        conta = 120 (consumo da casa sem ar) + 0,85 * horas_de_ar + ruído
    - 120 reais: geladeira, chuveiro, iluminação etc.
    - 0,85 real por hora: ~1 kWh de consumo x tarifa com impostos.
    """
    rng = np.random.default_rng(SEED)
    horas_mes = rng.uniform(0, 450, n_amostras)   # de 0 a 450 h/mês (~15 h/dia)
    ruido = rng.normal(0, 15, n_amostras)         # variações de tarifa e hábitos
    conta = 120 + 0.85 * horas_mes + ruido
    return horas_mes, conta


# ---------------------------------------------------------------------------
# 2) TREINO
# ---------------------------------------------------------------------------
@st.cache_resource  # treina uma única vez, mesmo com o Streamlit reexecutando o script
def treinar_modelo():
    """Treina a regressão linear e devolve modelo, escalas e parâmetros reais."""
    horas, conta = gerar_dados()

    # Normalização (z-score): deixa x e y com média 0 e desvio 1,
    # o que ajuda muito o gradiente descendente a convergir.
    x_media, x_desvio = horas.mean(), horas.std()
    y_media, y_desvio = conta.mean(), conta.std()
    x = (horas - x_media) / x_desvio
    y = (conta - y_media) / y_desvio

    # Regressão linear simples = 1 neurônio sem função de ativação: y = w*x + b
    modelo = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(1,)),
        tf.keras.layers.Dense(1),
    ])
    modelo.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.05),
                   loss="mse")  # MSE: erro quadrático médio
    modelo.fit(x, y, epochs=200, verbose=0)

    # Os pesos aprendidos estão na escala normalizada. Convertendo para reais:
    #   custo_por_hora = w * (y_desvio / x_desvio)
    #   custo_base     = b * y_desvio + y_media - custo_por_hora * x_media
    pesos, vies = modelo.layers[0].get_weights()
    custo_por_hora = float(pesos[0][0]) * y_desvio / x_desvio
    custo_base = float(vies[0]) * y_desvio + y_media - custo_por_hora * x_media

    escalas = {"x_media": x_media, "x_desvio": x_desvio,
               "y_media": y_media, "y_desvio": y_desvio}
    return modelo, escalas, custo_base, custo_por_hora


# ---------------------------------------------------------------------------
# 3) PREVISÃO E GRÁFICO
# ---------------------------------------------------------------------------
def prever_conta(modelo, escalas, horas_mes: float) -> float:
    """Usa o modelo do TensorFlow para projetar a conta mensal (em reais)."""
    x = (horas_mes - escalas["x_media"]) / escalas["x_desvio"]
    y_norm = modelo.predict(np.array([[x]]), verbose=0)[0][0]
    return max(0.0, float(y_norm * escalas["y_desvio"] + escalas["y_media"]))


def montar_evolucao(horas_dia: float, custo_base: float,
                    custo_por_hora: float) -> pd.DataFrame:
    """Calcula o gasto acumulado a cada dia do mês, com e sem ar-condicionado.

    - Casa sem ar: o custo base é "diluído" igualmente pelos 30 dias.
    - Com ar: soma-se, a cada dia, (horas do dia x custo por hora).
    No dia 30, o valor "com ar" coincide com a previsão mensal do modelo.
    """
    dias = np.arange(1, DIAS_MES + 1)
    sem_ar = custo_base / DIAS_MES * dias
    com_ar = sem_ar + custo_por_hora * horas_dia * dias
    return pd.DataFrame(
        {"Sem ar-condicionado (R$)": sem_ar, "Com ar-condicionado (R$)": com_ar},
        index=pd.Index(dias, name="Dia do mês"),
    )


def formatar_brl(valor: float) -> str:
    """Formata no padrão brasileiro: R$ 1.234,56."""
    texto = f"{valor:,.2f}"
    return "R$ " + texto.replace(",", "X").replace(".", ",").replace("X", ".")


# ---------------------------------------------------------------------------
# 4) INTERFACE (Streamlit)
# ---------------------------------------------------------------------------
def main():
    st.set_page_config(page_title="Conta de Luz no Verão", page_icon="❄️")
    st.title("❄️ Previsão da Conta de Luz no Verão")
    st.write("Informe as horas diárias de ar-condicionado e veja a projeção do mês.")

    try:
        with st.spinner("Treinando o modelo..."):
            modelo, escalas, custo_base, custo_por_hora = treinar_modelo()
    except Exception as erro:
        st.error(f"Não foi possível treinar o modelo: {erro}")
        return

    # Entrada do usuário: limitada a 0-24 h, pois o dia só tem 24 horas
    horas_dia = st.number_input("Horas de uso do ar-condicionado por dia",
                                min_value=0.0, max_value=24.0,
                                value=6.0, step=0.5)

    try:
        horas_mes = horas_dia * DIAS_MES
        conta_prevista = prever_conta(modelo, escalas, horas_mes)
        evolucao = montar_evolucao(horas_dia, custo_base, custo_por_hora)
    except Exception as erro:
        st.error(f"Erro ao calcular a projeção: {erro}")
        return

    col1, col2 = st.columns(2)
    col1.metric("Conta mensal prevista", formatar_brl(conta_prevista))
    col2.metric("Custo estimado por hora de ar", formatar_brl(custo_por_hora))

    st.subheader("Evolução do gasto ao longo do mês")
    st.line_chart(evolucao)

    st.caption(f"O modelo aprendeu um custo base de {formatar_brl(custo_base)} "
               "por mês (casa sem ar) + o custo de cada hora de ar-condicionado.")


if __name__ == "__main__":
    main()

!npx localtunnel --port 8501