# -*- coding: utf-8 -*-
"""Precificador_Carros_Usados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicEOMvEeXqzhSjc8oc_0RL2Hd4vkROU
"""

!pip install -q streamlit
!npm install -q -g localtunnel

!streamlit run app.py &>/content/logs.txt &
!curl -s https://loca.lt/mytunnelpassword

"""
Precificador de Carros Usados
-----------------------------
Treina uma regressão linear simples (KM rodados -> Preço) com TensorFlow
e permite prever o preço de um carro usando um slider no Streamlit.

Arquitetura (resumo):
    gerar_dados()    -> cria os dados de treino (sintéticos)
    treinar_modelo() -> normaliza os dados e treina o modelo (cacheado)
    prever_preco()   -> aplica o modelo e devolve o preço em reais
    main()           -> monta a interface (view) e liga tudo
"""

import numpy as np
import streamlit as st
import tensorflow as tf
import matplotlib.pyplot as plt

# Semente fixa: garante que os dados e o treino sejam reproduzíveis
SEED = 42
tf.keras.utils.set_random_seed(SEED)


# ---------------------------------------------------------------------------
# 1) DADOS
# ---------------------------------------------------------------------------
def gerar_dados(n_amostras: int = 300):
    """Gera dados sintéticos: quanto mais KM, menor o preço (+ ruído).

    Relação "verdadeira" usada na simulação:
        preco = 85.000 - 0,35 * km + ruído
    O modelo NÃO conhece esses números; ele precisa descobri-los.
    """
    rng = np.random.default_rng(SEED)
    km = rng.uniform(0, 200_000, n_amostras)
    ruido = rng.normal(0, 4_000, n_amostras)  # variação natural do mercado
    preco = 85_000 - 0.35 * km + ruido
    return km, preco


# ---------------------------------------------------------------------------
# 2) TREINO
# ---------------------------------------------------------------------------
@st.cache_resource  # treina UMA vez; o Streamlit reexecuta o script a cada interação
def treinar_modelo():
    """Treina a regressão linear e devolve o modelo + estatísticas de escala."""
    km, preco = gerar_dados()

    # Normalização (z-score): deixa km e preço em escala parecida (média 0,
    # desvio 1). Sem isso, o gradiente descendente converge muito mal,
    # pois KM vai até 200.000 e os pesos iniciais são minúsculos.
    stats = {
        "km_media": km.mean(), "km_desvio": km.std(),
        "preco_media": preco.mean(), "preco_desvio": preco.std(),
    }
    x = (km - stats["km_media"]) / stats["km_desvio"]
    y = (preco - stats["preco_media"]) / stats["preco_desvio"]

    # Regressão linear simples = 1 neurônio, 1 entrada, sem ativação:
    #     y = w * x + b
    modelo = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(1,)),
        tf.keras.layers.Dense(1),
    ])

    # Adam ajusta w e b; MSE (erro quadrático médio) é a função de perda
    modelo.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.05),
        loss="mse",
    )
    modelo.fit(x, y, epochs=150, verbose=0)  # 150 passadas pelos dados

    return modelo, stats, km, preco


# ---------------------------------------------------------------------------
# 3) PREVISÃO
# ---------------------------------------------------------------------------
def prever_preco(modelo, stats, km_informado: float) -> float:
    """Normaliza o KM, prevê e converte o resultado de volta para reais."""
    km_norm = (km_informado - stats["km_media"]) / stats["km_desvio"]
    previsao_norm = modelo.predict(np.array([[km_norm]]), verbose=0)[0][0]
    preco = previsao_norm * stats["preco_desvio"] + stats["preco_media"]
    return max(0.0, float(preco))  # preço nunca fica negativo


def formatar_brl(valor: float) -> str:
    """Formata no padrão brasileiro: R$ 1.234,56."""
    texto = f"{valor:,.2f}"  # 1,234.56 (padrão americano)
    return "R$ " + texto.replace(",", "X").replace(".", ",").replace("X", ".")


# ---------------------------------------------------------------------------
# 4) INTERFACE (Streamlit)
# ---------------------------------------------------------------------------
def main():
    st.set_page_config(page_title="Precificador de Carros Usados", page_icon="🚗")
    st.title("🚗 Precificador de Carros Usados")
    st.write("Regressão linear com TensorFlow: **KM rodados → Preço**.")

    try:
        with st.spinner("Treinando o modelo..."):
            modelo, stats, km, preco = treinar_modelo()
    except Exception as erro:
        st.error(f"Não foi possível treinar o modelo: {erro}")
        return

    # Slider: o usuário escolhe a quilometragem
    km_escolhido = st.slider(
        "KM rodados", min_value=0, max_value=200_000, value=50_000, step=1_000
    )

    try:
        preco_previsto = prever_preco(modelo, stats, km_escolhido)
    except Exception as erro:
        st.error(f"Erro ao prever o preço: {erro}")
        return

    st.metric("Preço previsto", formatar_brl(preco_previsto))

    # Gráfico: pontos de treino + reta aprendida + ponto escolhido
    fig, ax = plt.subplots()
    ax.scatter(km, preco, alpha=0.3, label="Dados de treino")
    eixo_km = np.linspace(0, 200_000, 50)
    ax.plot(eixo_km, [prever_preco(modelo, stats, k) for k in eixo_km],
            color="red", label="Reta do modelo")
    ax.scatter([km_escolhido], [preco_previsto], color="black", s=80,
               zorder=5, label="Sua previsão")
    ax.set_xlabel("KM rodados")
    ax.set_ylabel("Preço (R$)")
    ax.legend()
    st.pyplot(fig)


if __name__ == "__main__":
    main()

!npx localtunnel --port 8501