# -*- coding: utf-8 -*-
"""Recomendador_Estilo_Musica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicEOMvEeXqzhSjc8oc_0RL2Hd4vkROU
"""

!pip install -q streamlit
!npm install -q -g localtunnel

!streamlit run app.py &>/content/logs.txt &
!curl -s https://loca.lt/mytunnelpassword

"""
Playlist por Humor
------------------
O colaborador ajusta dois sliders (Energia e Tristeza) e uma rede neural
(TensorFlow) classifica o humor em um gênero: Rock, Pop, Lofi ou Sertanejo.

Estrutura do arquivo:
    GENEROS / CENTROS   -> configuração (dados "de domínio")
    gerar_dados()       -> cria exemplos de treino a partir dos centros
    treinar_modelo()    -> treina o classificador (executa uma única vez)
    recomendar()        -> devolve as probabilidades por gênero
    aplicar_estilo()    -> CSS para o visual escuro estilo Spotify
    main()              -> interface (barra lateral + 2 colunas)
"""

import numpy as np
import pandas as pd
import streamlit as st
import tensorflow as tf

SEED = 42  # semente fixa: treino reproduzível
tf.keras.utils.set_random_seed(SEED)

# ---------------------------------------------------------------------------
# 1) CONFIGURAÇÃO
# ---------------------------------------------------------------------------
# Cada gênero tem aparência, descrição e artistas de exemplo.
GENEROS = {
    "Rock": {
        "emoji": "🎸", "cor": "#E8115B",
        "descricao": "Energia alta com emoção intensa: ótimo para canalizar a tensão.",
        "artistas": ["Legião Urbana", "Titãs", "Foo Fighters", "Queen"],
    },
    "Pop": {
        "emoji": "🎤", "cor": "#1DB954",
        "descricao": "Energia alta e astral leve: bom para animar a equipe.",
        "artistas": ["Anitta", "Ivete Sangalo", "Dua Lipa", "Bruno Mars"],
    },
    "Lofi": {
        "emoji": "🎧", "cor": "#509BF5",
        "descricao": "Ritmo calmo e constante: ajuda a focar e desacelerar.",
        "artistas": ["Lofi Girl", "Tomppabeats", "Jinsang", "Idealism"],
    },
    "Sertanejo": {
        "emoji": "🤠", "cor": "#F59B23",
        "descricao": "Energia moderada com sentimento profundo: a boa e velha sofrência.",
        "artistas": ["Marília Mendonça", "Zé Neto & Cristiano",
                     "Jorge & Mateus", "Chitãozinho & Xororó"],
    },
}
NOMES = list(GENEROS)  # a ordem define o índice de cada classe (0, 1, 2, 3)

# Ponto "típico" de cada gênero no plano (energia, tristeza), escala de 0 a 10.
CENTROS = {
    "Rock": (8.5, 6.0),
    "Pop": (8.0, 1.5),
    "Lofi": (2.5, 5.0),
    "Sertanejo": (5.0, 8.5),
}


# ---------------------------------------------------------------------------
# 2) DADOS E TREINO
# ---------------------------------------------------------------------------
def gerar_dados(por_genero: int = 250):
    """Cria exemplos sintéticos: pontos espalhados ao redor de cada centro.

    Os dados são simulados para fins didáticos; em produção, seriam
    substituídos por respostas reais de uma pesquisa com os colaboradores.
    """
    rng = np.random.default_rng(SEED)
    entradas, rotulos = [], []
    for indice, nome in enumerate(NOMES):
        pontos = rng.normal(CENTROS[nome], 1.3, size=(por_genero, 2))
        entradas.append(np.clip(pontos, 0, 10))   # mantém dentro de 0-10
        rotulos += [indice] * por_genero
    return np.vstack(entradas), np.array(rotulos)


@st.cache_resource  # treina uma só vez; o Streamlit reexecuta o script a cada clique
def treinar_modelo():
    """Treina uma rede neural pequena para classificar o humor em 4 gêneros."""
    x, y = gerar_dados()
    x = x / 10.0  # normalização simples: escala 0-10 vira 0-1

    # Entrada (2 valores) -> 2 camadas ocultas -> 4 probabilidades (softmax)
    modelo = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(2,)),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(len(NOMES), activation="softmax"),
    ])
    modelo.compile(optimizer="adam",
                   loss="sparse_categorical_crossentropy",  # rótulos são inteiros
                   metrics=["accuracy"])

    # validation_split: separa 20% dos dados para medir se o modelo generaliza
    historico = modelo.fit(x, y, epochs=60, batch_size=32,
                           validation_split=0.2, shuffle=True, verbose=0)
    acuracia = float(historico.history["val_accuracy"][-1])
    return modelo, acuracia


# ---------------------------------------------------------------------------
# 3) PREVISÃO
# ---------------------------------------------------------------------------
def recomendar(modelo, energia: float, tristeza: float) -> np.ndarray:
    """Devolve a probabilidade (0-1) de cada gênero para o humor informado."""
    entrada = np.array([[energia / 10.0, tristeza / 10.0]])
    return modelo.predict(entrada, verbose=0)[0]


# ---------------------------------------------------------------------------
# 4) INTERFACE
# ---------------------------------------------------------------------------
def aplicar_estilo():
    """CSS para o visual escuro com destaque verde, inspirado no Spotify."""
    st.markdown(
        """
        <style>
        .stApp { background-color: #121212; color: #FFFFFF; }
        [data-testid="stSidebar"] { background-color: #000000; }
        h1, h2, h3, label, p { color: #FFFFFF !important; }
        .card { background: #181818; border-radius: 12px; padding: 24px;
                border-left: 8px solid var(--cor); }
        .card h2 { margin: 0 0 8px 0; }
        .card ul { margin: 8px 0 0 0; padding-left: 20px; color: #B3B3B3; }
        .legenda { color: #B3B3B3 !important; font-size: 0.85rem; }
        </style>
        """,
        unsafe_allow_html=True,
    )


def main():
    st.set_page_config(page_title="Playlist por Humor", page_icon="🎵", layout="wide")
    aplicar_estilo()

    try:
        with st.spinner("Preparando o modelo..."):
            modelo, acuracia = treinar_modelo()
    except Exception as erro:
        st.error(f"Não foi possível preparar o modelo: {erro}")
        return

    # --- Coluna lateral (esquerda): controles, como o menu do Spotify ---
    with st.sidebar:
        st.header("🎚️ Seu humor agora")
        energia = st.slider("Energia", 0, 10, 5, help="0 = sem pique, 10 = a mil")
        tristeza = st.slider("Tristeza", 0, 10, 5, help="0 = animado, 10 = bem pra baixo")
        st.markdown(
            "<p class='legenda'>Nenhuma informação é armazenada: "
            "os valores existem apenas durante esta sessão.</p>",
            unsafe_allow_html=True,
        )

    # --- Cálculo da recomendação ---
    try:
        probabilidades = recomendar(modelo, energia, tristeza)
    except Exception as erro:
        st.error(f"Erro ao gerar a recomendação: {erro}")
        return
    vencedor = NOMES[int(np.argmax(probabilidades))]
    dados = GENEROS[vencedor]

    st.title("🎵 Playlist por Humor")
    st.caption("Recomendação musical para colaboradores, com base no seu estado atual.")

    # --- Área principal em duas colunas: destaque (centro) e painel (direita) ---
    col_principal, col_painel = st.columns([3, 2])

    with col_principal:
        artistas = "".join(f"<li>{nome}</li>" for nome in dados["artistas"])
        st.markdown(
            f"""
            <div class="card" style="--cor: {dados['cor']}">
                <p class="legenda">RECOMENDAÇÃO PARA AGORA</p>
                <h2>{dados['emoji']} {vencedor}</h2>
                <p>{dados['descricao']}</p>
                <p class="legenda">Para começar a playlist:</p>
                <ul>{artistas}</ul>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with col_painel:
        st.subheader("Confiança do modelo")
        tabela = pd.DataFrame({"Probabilidade (%)": probabilidades * 100},
                              index=NOMES)
        st.bar_chart(tabela)

    st.caption(f"Acurácia de validação do modelo: {acuracia:.0%} "
               "(medida em dados simulados).")


if __name__ == "__main__":
    main()

!npx localtunnel --port 8501