# -*- coding: utf-8 -*-
"""Avaliacao_Positivas_Negativas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicEOMvEeXqzhSjc8oc_0RL2Hd4vkROU
"""

!pip install -q streamlit spacy
!python -m spacy download pt_core_news_sm -q
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import spacy
# 
# # Configuração visual da página Streamlit
# st.set_page_config(
#     page_title="Classificador NLP com spaCy",
#     page_icon="🧠",
#     layout="centered"
# )
# 
# # Carregamento do modelo spaCy com cache para não recarregar a cada interação
# @st.cache_resource
# def load_spacy_model():
#     """
#     Carrega e armazena em cache o pipeline em português do spaCy.
#     """
#     try:
#         return spacy.load("pt_core_news_sm")
#     except Exception as e:
#         st.error(f"Erro ao carregar o modelo do spaCy: {str(e)}")
#         return None
# 
# nlp = load_spacy_model()
# 
# # Dicionários de palavras-chave baseados nos lemas (formas canônicas)
# POSITIVE_LEMMAS = {
#     "excelente", "ótimo", "bom", "adorar", "gostar", "recomendar",
#     "incrível", "rápido", "perfeito", "eficiente", "satisfeito",
#     "maravilhoso", "qualidade", "atencioso"
# }
# 
# NEGATIVE_LEMMAS = {
#     "ruim", "péssimo", "horrível", "demorado", "atraso", "defeito",
#     "decepcionado", "decepção", "odiar", "pior", "cancelar",
#     "problema", "lento", "quebrado", "pessimo", "horrivel"
# }
# 
# NEGATION_LEMMAS = {"não", "nao", "nunca", "jamais", "sem", "nada"}
# 
# 
# def analyze_sentiment_spacy(text: str) -> dict:
#     """
#     Processa o texto com o pipeline do spaCy, extrai lemas,
#     trata negações e classifica o sentimento do comentário.
#     """
#     try:
#         if not text or not text.strip():
#             return {
#                 "sentiment": "Neutro",
#                 "pos_count": 0,
#                 "neg_count": 0,
#                 "pos_found": [],
#                 "neg_found": [],
#                 "tokens_info": []
#             }
# 
#         # Processamento do texto pelo pipeline spaCy (gera o objeto Doc)
#         doc = nlp(text)
# 
#         pos_found = []
#         neg_found = []
#         tokens_info = []
# 
#         # Iteração sobre cada token identificado pelo spaCy
#         for i, token in enumerate(doc):
#             # Ignora pontuações e espaços
#             if token.is_punct or token.is_space:
#                 continue
# 
#             lemma = token.lemma_.lower()
#             word = token.text.lower()
# 
#             # Guarda informações estruturadas de cada token para fins didáticos
#             tokens_info.append({
#                 "texto": token.text,
#                 "lemma": token.lemma_,
#                 "pos": token.pos_
#             })
# 
#             # Checagem de negação em uma janela de 2 tokens anteriores
#             has_negation = False
#             if i > 0 and doc[i - 1].lemma_.lower() in NEGATION_LEMMAS:
#                 has_negation = True
#             elif i > 1 and doc[i - 2].lemma_.lower() in NEGATION_LEMMAS:
#                 has_negation = True
# 
#             # Classificação por lema
#             if lemma in POSITIVE_LEMMAS or word in POSITIVE_LEMMAS:
#                 if has_negation:
#                     neg_found.append(f"não {word}")
#                 else:
#                     pos_found.append(word)
# 
#             elif lemma in NEGATIVE_LEMMAS or word in NEGATIVE_LEMMAS:
#                 if has_negation:
#                     pos_found.append(f"não {word}")
#                 else:
#                     neg_found.append(word)
# 
#         pos_count = len(pos_found)
#         neg_count = len(neg_found)
# 
#         # Regras condicionais de decisão
#         if pos_count > neg_count:
#             sentiment = "Positivo"
#         elif neg_count > pos_count:
#             sentiment = "Negativo"
#         else:
#             sentiment = "Neutro"
# 
#         return {
#             "sentiment": sentiment,
#             "pos_count": pos_count,
#             "neg_count": neg_count,
#             "pos_found": pos_found,
#             "neg_found": neg_found,
#             "tokens_info": tokens_info
#         }
# 
#     except Exception as e:
#         st.error(f"Erro interno no processamento com spaCy: {str(e)}")
#         return {
#             "sentiment": "Erro",
#             "pos_count": 0,
#             "neg_count": 0,
#             "pos_found": [],
#             "neg_found": [],
#             "tokens_info": []
#         }
# 
# 
# def main():
#     """
#     Interface gráfica principal do Streamlit.
#     """
#     try:
#         st.title("🧠 Análise de Sentimentos com spaCy (NLP)")
#         st.caption("Atividade 1: Processamento de Linguagem Natural com Lematização e Tokenização")
# 
#         user_comment = st.text_area(
#             "Digite o comentário do cliente para análise:",
#             height=110,
#             placeholder="Exemplo: Os produtos entregues foram excelentes e eu gostei muito!"
#         )
# 
#         if st.button("Analisar com spaCy", type="primary"):
#             if user_comment.strip():
#                 result = analyze_sentiment_spacy(user_comment)
#                 sentiment = result["sentiment"]
# 
#                 st.divider()
# 
#                 # Exibição do resultado do sentimento
#                 if sentiment == "Positivo":
#                     st.success("🟢 **Sentimento Classificado: POSITIVO**")
#                 elif sentiment == "Negativo":
#                     st.error("🔴 **Sentimento Classificado: NEGATIVO**")
#                 else:
#                     st.warning("🟡 **Sentimento Classificado: NEUTRO**")
# 
#                 # Métricas principais
#                 col1, col2 = st.columns(2)
#                 with col1:
#                     st.metric("Termos Positivos", result["pos_count"])
#                     if result["pos_found"]:
#                         st.caption(f"Identificados: {', '.join(result['pos_found'])}")
# 
#                 with col2:
#                     st.metric("Termos Negativos", result["neg_count"])
#                     if result["neg_found"]:
#                         st.caption(f"Identificados: {', '.join(result['neg_found'])}")
# 
#                 # Painel Didático: Análise Técnica dos Tokens gerados pelo spaCy
#                 with st.expander("🔍 Ver Detalhes do Pipeline NLP (spaCy Tokens e Lemas)"):
#                     st.json(result["tokens_info"])
# 
#             else:
#                 st.info("Digite um texto antes de clicar no botão.")
# 
#     except Exception as e:
#         st.error(f"Falha ao executar a interface: {str(e)}")
# 
# 
# if __name__ == "__main__":
#     main()

!streamlit run app.py &>/content/logs.txt &
!cloudflared tunnel --url http://localhost:8501

