# -*- coding: utf-8 -*-
"""Detector_Pessoas_Objetos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicEOMvEeXqzhSjc8oc_0RL2Hd4vkROU
"""

!pip install -q streamlit opencv-python-headless numpy Pillow
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import cv2
# import numpy as np
# from PIL import Image
# import io
# 
# # Configuração visual inicial da página no Streamlit
# st.set_page_config(
#     page_title="Detector Visual por Regras",
#     page_icon="👁️",
#     layout="wide"
# )
# 
# 
# @st.cache_resource
# def load_cascade_classifiers():
#     """
#     Carrega os classificadores Haar Cascade pré-treinados do OpenCV.
#     A anotação @st.cache_resource evita recarregar os arquivos a cada clique.
#     """
#     try:
#         # Carrega o modelo de detecção de rostos frontais
#         face_cascade = cv2.CascadeClassifier(
#             cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
#         )
#         # Carrega o modelo de detecção de olhos
#         eye_cascade = cv2.CascadeClassifier(
#             cv2.data.haarcascades + 'haarcascade_eye.xml'
#         )
#         return face_cascade, eye_cascade
#     except Exception as e:
#         st.error(f"Erro ao carregar classificadores do OpenCV: {str(e)}")
#         return None, None
# 
# 
# def process_image_rules(image_bytes: bytes) -> dict:
#     """
#     Processa a imagem enviada pelo usuário:
#     1. Converte a imagem em matriz numérica BGR (padrão OpenCV).
#     2. Aplica filtro de escala de cinza.
#     3. Detecta rostos e olhos via Haar Cascade.
#     4. Detecta objetos/contornos proeminentes via filtro Canny.
#     """
#     try:
#         # Converte os bytes recebidos em imagem PIL e depois para matriz NumPy
#         image_pil = Image.open(io.BytesIO(image_bytes)).convert("RGB")
#         img_np = np.array(image_pil)
# 
#         # O OpenCV utiliza o espaço de cor BGR por padrão
#         img_bgr = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
#         gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
# 
#         face_cascade, eye_cascade = load_cascade_classifiers()
# 
#         # Detecção de rostos com o algoritmo Haar Cascade
#         faces = face_cascade.detectMultiScale(
#             gray,
#             scaleFactor=1.1,
#             minNeighbors=5,
#             minSize=(30, 30)
#         )
# 
#         faces_detected = len(faces)
# 
#         # Desenha caixas retangulares (bounding boxes) nos rostos encontrados
#         for (x, y, w, h) in faces:
#             # Retângulo verde para o rosto
#             cv2.rectangle(img_bgr, (x, y), (x + w, y + h), (0, 255, 0), 3)
#             cv2.putText(
#                 img_bgr,
#                 "Pessoa/Rosto",
#                 (x, y - 10),
#                 cv2.FONT_HERSHEY_SIMPLEX,
#                 0.7,
#                 (0, 255, 0),
#                 2
#             )
# 
#             # Recorta a Região de Interesse (ROI) do rosto para buscar olhos
#             roi_gray = gray[y:y+h, x:x+w]
#             roi_color = img_bgr[y:y+h, x:x+w]
#             eyes = eye_cascade.detectMultiScale(roi_gray)
#             for (ex, ey, ew, eh) in eyes:
#                 # Retângulo azul para os olhos
#                 cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (255, 0, 0), 1)
# 
#         # Detecção de Objetos/Formas por Contornos e Bordas
#         blurred = cv2.GaussianBlur(gray, (5, 5), 0)
#         edges = cv2.Canny(blurred, 50, 150)
# 
#         contours, _ = cv2.findContours(
#             edges,
#             cv2.RETR_EXTERNAL,
#             cv2.CHAIN_APPROX_SIMPLE
#         )
# 
#         objects_count = 0
#         h_img, w_img, _ = img_bgr.shape
#         min_area = (h_img * w_img) * 0.02  # O objeto precisa ocupar pelo menos 2% da tela
# 
#         for cnt in contours:
#             area = cv2.contourArea(cnt)
#             if area > min_area:
#                 x, y, w, h = cv2.boundingRect(cnt)
#                 # Retângulo laranja para objetos/formas destacadas
#                 cv2.rectangle(img_bgr, (x, y), (x + w, y + h), (0, 165, 255), 2)
#                 cv2.putText(
#                     img_bgr,
#                     "Objeto Destacado",
#                     (x, y - 5),
#                     cv2.FONT_HERSHEY_SIMPLEX,
#                     0.5,
#                     (0, 165, 255),
#                     1
#                 )
#                 objects_count += 1
# 
#         # Converte de volta para RGB para o Streamlit exibir com as cores corretas
#         result_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
# 
#         return {
#             "processed_image": result_rgb,
#             "faces_count": faces_detected,
#             "objects_count": objects_count,
#             "resolution": f"{w_img}x{h_img} px"
#         }
# 
#     except Exception as e:
#         st.error(f"Erro no processamento da imagem: {str(e)}")
#         return None
# 
# 
# def main():
#     """
#     Constrói a interface do usuário no Streamlit.
#     """
#     try:
#         st.title("👁️ Detector de Pessoas e Objetos (Visão Computacional)")
#         st.caption("Sistema de Análise por Regras com OpenCV e Haar Cascades")
# 
#         # Campo de upload de imagem
#         uploaded_file = st.file_uploader(
#             "Envie uma imagem para análise (JPG, JPEG, PNG):",
#             type=["jpg", "jpeg", "png"]
#         )
# 
#         if uploaded_file is not None:
#             image_bytes = uploaded_file.read()
# 
#             col1, col2 = st.columns(2)
# 
#             with col1:
#                 st.subheader("Imagem Original")
#                 st.image(image_bytes, use_container_width=True)
# 
#             if st.button("Executar Análise por Regras", type="primary"):
#                 with st.spinner("Processando imagem com OpenCV..."):
#                     result = process_image_rules(image_bytes)
# 
#                 if result:
#                     with col2:
#                         st.subheader("Imagem Processada")
#                         st.image(result["processed_image"], use_container_width=True)
# 
#                     st.divider()
#                     st.subheader("📊 Métricas da Análise Visual")
# 
#                     m1, m2, m3 = st.columns(3)
#                     m1.metric("Rostos/Pessoas Detectados", result["faces_count"])
#                     m2.metric("Formas/Objetos Destacados", result["objects_count"])
#                     m3.metric("Resolução da Imagem", result["resolution"])
# 
#     except Exception as e:
#         st.error(f"Erro ao carregar a interface da aplicação: {str(e)}")
# 
# 
# if __name__ == "__main__":
#     main()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# opencv-python-headless
# numpy
# Pillow

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # Detector Visual de Pessoas e Objetos com OpenCV 👁️
# 
# Aplicação web desenvolvida em Python e Streamlit para simulação de Visão Computacional baseada em regras e classificadores Haar Cascade.
# 
# ## 🚀 Funcionalidades
# - **Detecção de Pessoas/Rostos:** Utiliza o algoritmo Haar Cascade para localizar rostos e olhos em tempo real.
# - **Segmentação por Contornos:** Identifica objetos e formas proeminentes na imagem sem necessidade de redes neurais pesadas.
# - **Baixo Consumo de Recursos:** Projetado para rodar em servidores com limite rígido de memória (< 100 MB RAM).
# 
# ## 🛠️ Tecnologias
# - Python 3.10+
# - Streamlit
# - OpenCV (Headless)
# - NumPy
# - Pillow
# 
# ## ⚙️ Configuração para Deploy no Render
# - **Environment:** Python 3
# - **Build Command:** `pip install -r requirements.txt`
# - **Start Command:** `streamlit run app.py --server.port $PORT --server.address 0.0.0.0`

!streamlit run app.py &>/content/logs.txt &
!cloudflared tunnel --url http://localhost:8501

